// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEDW_WfXGeAtdIUnF_mW6Gsz0zOmur0A',
    appId: '1:228202207049:web:ff065c0fef7a8e28ec2c98',
    messagingSenderId: '228202207049',
    projectId: 'enggexchangeapp',
    authDomain: 'enggexchangeapp.firebaseapp.com',
    storageBucket: 'enggexchangeapp.appspot.com',
    measurementId: 'G-S77SW20TF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuV8Eakzwu-Xan3wn7owTLVzUGGnc9rkg',
    appId: '1:228202207049:android:fafddf56a812720bec2c98',
    messagingSenderId: '228202207049',
    projectId: 'enggexchangeapp',
    storageBucket: 'enggexchangeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyok3mVttmHolOMeyg-1br5ziTQxf72o',
    appId: '1:228202207049:ios:5151532d908248ddec2c98',
    messagingSenderId: '228202207049',
    projectId: 'enggexchangeapp',
    storageBucket: 'enggexchangeapp.appspot.com',
    iosClientId: '228202207049-34l9a9b75lpqb19cb0o9lnm0tenjrlfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManager',
  );
}
